env: local
http:
  host: 0.0.0.0
  port: 8080
db:
  url: postgres://user_service:password@user-db:5432/users?sslmode=disable
  migrate: true
auth:
  access_secret: super-secret-access-key
  lifetime:
    access: 10m
    refresh: 720h
